### ISSUE TITLE
Firefox credentials uploaded

### ISSUE THREAD

**Issue by Plazmaz** [sohaeb/.dotfiles#1]
You may want to be careful... You uploaded your entire firefox folder, which means that all of your username/passwords are accessible. I STRONGLY suggest removing these files and switching to a password manager such as LastPass or 1Password.

**Comment by Plazmaz** [comment]
For example, I can see your PayPal, facebook(x2), gmails, and several web hosting sites.

**Comment by sohaeb** [comment]
You are awesome man. Thanks for letting me know.
